### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by remixz** [remixz/publish-release#16]
Soo... sorry for my radio silence! I'm not the greatest at keeping up with a bunch of open source projects.

I'm not actively using this project myself anymore, so I'd like to find some new maintainers who use this a bit more, and let them handle this module how they wish to.

@Aluxian @maxcnunes I already have you two as collaborators on this repo; if you'd like, I'll add you to the npm package as well, so you can publish new versions. If you're interested, just put your npm username and I'll add you to the package ASAP.

If there are any other active users who'd like to become maintainers, leave a comment here. Thanks!

**Comment by maxcnunes** [comment]
Sorry @remixz. I have not used this library anymore. Someone actively using it would be a better option.

**Comment by Aluxian** [comment]
Hey, I can help you! I'll help maintain this project and the npm package. My npm username is `aluxian`.

**Comment by remixz** [comment]
@maxcnunes No worries! :smile: 

@Aluxian Awesome, thanks! I've just added you to the package. Go ahead and maintain this module how you best see fit.

**Comment by Aluxian** [comment]
Thanks! I feel an intrinsic responsibility and desire to not disappoint you and take care of the project as best as I can. And so I will. Cheers! 😁


--
Alexandru Rosianu Full-Stack Developer aluxian.com | startersquad.com On Wed, May 04, 2016 at 10:13 AM, Zach Bruggeman < notifications@github.com [notifications@github.com] > wrote:
@maxcnunes [https://github.com/maxcnunes] No worries!

@Aluxian [https://github.com/Aluxian] Awesome, thanks! I've just added you to the package. Go ahead and maintain this module how you best see fit.

**Comment by Aluxian** [comment]
I think this can be closed now :)
