### ISSUE TITLE
Error handling bug

### ISSUE THREAD

**Issue by karlroberts** [remixz/publish-release#18]
see https://github.com/Aluxian/gulp-github-release/issues/3

I have fixed this bug in this project and in https://github.com/Aluxian/gulp-github-release and will create the Pull requests.

Basically this code as an `EventEmitter` should emit 'error' events. 
It also needed to handle the case where `createRelease` had a http error status code , ie >= 400, because although it handled a `request` err  `request` does not think a 400 code is an error... it is correct beacuse it is a valid http response :-).

However if the `createRelease` gets a 400 or above (eg 401 not authorised, due to bad token) then it need to flag an error or else the downstream `uploadAssets` gets a bogus body object and fails.

Anyway, PR coming shortly.

**Comment by Aluxian** [comment]
Thank you!
