### ISSUE TITLE
Leaks credentials in case of exceptions

### ISSUE THREAD

**Issue by marionebl** [remixz/publish-release#20]
When throwing `publish-release` prints all available configuration, including the `Authorization` header. This leaks credentials as the header holds Github private access tokens in most cases, e.g.:
https://travis-ci.org/sinnerschrader/sinnerschrader-website-static/builds/179470281#L1625. 

---
(Token is refreshed)

**Comment by Aluxian** [comment]
Nice catch. Unfortunately, I don't have now to fix it soon, so PRs are welcome. Thank you.

**Comment by marionebl** [comment]
@Aluxian Submitted a PR, a swift release would be dope.

**Comment by Aluxian** [comment]
I know the feeling :) I'll take a look when I get home (3h). 

--

Alexandru Rosianu
Full-Stack Developer | aluxian.com

**Comment by marionebl** [comment]
@Aluxian No worries! I thought more in the matter of days

**Comment by Aluxian** [comment]
Merged and published. Thank you!

**Comment by marionebl** [comment]
🚀
