### ISSUE TITLE
Dont use wizzard

### ISSUE THREAD

**Issue by kanekotic** [remixz/publish-release#22]
First of all thanks for this package (looks very useful), This is a question actually not a bug. 

I want to run publish-release from my build system in this case i would like to use all the defaults from package.json and not be prompted by the wizzard. Is this possible with the current version?

**Comment by Aluxian** [comment]
In order to understand the issue you're facing, can you describe what you've tried and the current behaviour of the package?

**Comment by kanekotic** [comment]
so basically I want my jenkins build to deploy to github automatically.
i have added to my `scripts`:
```
"release": "publish-release --reuseRelease --assets *-.tar.gz --token $TOKEN"
```
I was expecting this plus the information in `package.json` could be enough to not fire the wizzard. 
So my question would be what are the minimum set of parameters + package.json configuration that will not request me any command line information request (as my build will not be able to answer 😛 ).

**Comment by Aluxian** [comment]
Try supplying `--notes 'some notes'`

**Comment by kanekotic** [comment]
nop... seems not to be that, still asks for tag, user, repo (even if it has defaults set and its a just hit enter actions).

do you have an example package.json?, to check if everything is in the correct format.

**Comment by kanekotic** [comment]
ok i understood now. package.json needs an extra object with
"publishRelease": {
    "owner": "<user>",
    "repo": "<repo>",
    "tag": "<>",
    "name": "<>",
    "notes": "something"
  }
Is not that it will get the values from the current package.json

thanks for the time and the help

**Comment by Aluxian** [comment]
Oh, alright. I think I understand better now. Sorry, it's been a while since I've used this project myself so I forgot something. I'm glad it's fixed!
