### ISSUE TITLE
Expected behaviour for second asset upload

### ISSUE THREAD

**Issue by marcoancona** [remixz/publish-release#24]
Assuming `reuseRelease: true`, what is the expected behaviour of running release twice? At the moment the message `Uploading asset MyApp.zip` is displayed but the asset is not actually uploaded or replaced the second time the program runs. 

I think this should *replace* the assets with the same name, eventually with a parameter to disable this behaviour and throw an error instead.

**Comment by Aluxian** [comment]
I'm not sure whether it replaces the existing ones (which indeed seems wrong, it should replace them), but I've noticed that new files *are* appended to the existing release.

**Comment by Aluxian** [comment]
When you try to reupload a file, does it show upload progress and then say upload is complete?

**Comment by marcoancona** [comment]
Yes, if you reupload it shows the progress and it says upload complete (but the process is almost immediate, even if the file is several megabytes, which makes me think GitHub refuses the file but this event is not handled correctly)

**Comment by Aluxian** [comment]
It should be handled here: https://github.com/remixz/publish-release/blob/master/index.js#L159 <https://github.com/remixz/publish-release/blob/master/index.js#L159>

Or maybe GitHub returns success and an ‘already exists’ body. I *think* you might be able to capture that here: https://github.com/remixz/publish-release/blob/master/index.js#L162 <https://github.com/remixz/publish-release/blob/master/index.js#L162>, but I’m not sure. I don’t have time to investigate. You could also try piping (chain it here at the end: https://github.com/remixz/publish-release/blob/master/index.js#L167 <https://github.com/remixz/publish-release/blob/master/index.js#L167>) into another stream (created by you) which prints everything to console.
--

Alexandru Rosianu
Co-founder & CTO — futuristico.xyz

**Comment by marceloavf** [comment]
Any update on this? It's not replacing existing assets that has the same name.
