### ISSUE TITLE
Not publishing release only save as draft

### ISSUE THREAD

**Issue by AbinayaSubbiah** [remixz/publish-release#26]
Hi 

i am using below command to publish release. tag published successfully but in release tab i cant see publish release it showing as pre-release/draft

**publish-release --target_commitish master --draft true --prerelease true --name title --notes \"Release notes here\" --repo xxx --owner xxxx --tag  \"v5\"**

![image](https://user-images.githubusercontent.com/21117461/31385518-28e177e2-ade1-11e7-8bec-ab2b11058972.png)

how i can publish saved draft ?

**Comment by aluxian** [comment]
You can run the command again but without `--draft true` this time, it should update and publish it.

**Comment by AbinayaSubbiah** [comment]
@aluxian  thanks!! its worked but still i can see the old draft release

![image](https://user-images.githubusercontent.com/21117461/31393124-9bd5039c-adf8-11e7-9d45-feb7b3937088.png)

Could please suggest me to remove that draft?

**Comment by AbinayaSubbiah** [comment]
I can create a release without giving `--draft true`. Thanks!
