### ISSUE TITLE
Improve control error

### ISSUE THREAD

**Issue by piranna** [remixz/publish-release#3]
Every time that there's a problem uploading a release, it throws an ```TypeError: Cannot read property 'split' of undefined``` error at https://github.com/remixz/publish-release/blob/a7840b1ab5ca1fdd8e41e00641bdc2d1be5c098e/index.js#L77

**Comment by Aluxian** [comment]
Should be fixed by this line: https://github.com/remixz/publish-release/blob/master/index.js#L105
